### ISSUE TITLE
Does version constraint on mtl really need to be `<2.3`

### ISSUE THREAD

**Issue by ivanperez-keera** [fdedden/language-c99-simple#7]
I'm able to compile language-c99-simple with mtl 2.3 if I adjust the version bounds in the cabal file to read:

```
mtl >= 2.2.0 && < 2.4
```

Does the version bound on mtl need to be so strict?

**Comment by fdedden** [comment]
The bounds have simply not been updated yet. I will take a look if there are any particular reasons why it would not work with 2.3. Note however that that version is currently deprecated on hackage https://hackage.haskell.org/package/mtl.

I will take a look so that we can update the bounds in the future.

**Comment by ivanperez-keera** [comment]
Funny. I wonder why that is.

**Comment by fdedden** [comment]
Judging from the changelog (https://hackage.haskell.org/package/mtl-2.3/changelog) there is no reason why 2.3 wouldn't work with language-c99-simple. Given that 2.3 is deprecated, I cannot build language-c99-simple with it without jumping through some hoops. Unless there is a strong reason to allow 2.3 in this moment, I will keep it as is and update the bounds when mtl has been fixed.

Seems that with 2.3 there have been some changes that weren't supposed to be there:
- https://github.com/haskell/mtl/issues/123
- https://github.com/haskell/mtl/issues/117
- https://github.com/haskell/mtl/pull/121

Seems that a new release is planned, but isn't there yet.
https://github.com/haskell/mtl/pull/128

**Comment by RyanGlScott** [comment]
`mtl-2.3.1` has now been released. Can you raise the upper version bounds in `language-c99-simple` accordingly? I've verified that `language-c99-simple` builds aginst `mtl-2.3.1` without any issues.

**Comment by RyanGlScott** [comment]
I've opened https://github.com/fdedden/language-c99-simple/pull/15 with a fix.
